Repository Nactore-Org/Nacto-Care, pull requests merged in 2024-05, with the labels that each got.

#54 feat: automate greetings using github bot
  .github/workflows/greetings.yml
Labels: gssoc, level1

#92 Feat: Added testimonials section.
  src/Pages/LandingPage.jsx
  src/components/Testimonials/Testimonials.jsx
  src/components/Testimonials/testimonials.js
Labels: gssoc, level1

#86 Added Dark Mode Toggle
  package.json
  public/assets/dark.png
  public/assets/light.png
  src/Pages/BlogPage.jsx
  src/Pages/Blogs.jsx
  src/Pages/ContactPage.jsx
  src/Pages/LandingPage.jsx
  src/Pages/Licensing.jsx
  src/Pages/LoginPage.jsx
  src/Pages/PrivacyPolicy.jsx
  src/Pages/SignupPage.jsx
  src/Pages/TermsAndConditions.jsx
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/index.css
  src/main.jsx
  tailwind.config.js
Labels: gssoc, level3

#95 Resolved the Vercel 404 "Page Not Found" Error
  src/components/Footer/Footer.jsx
  src/main.jsx
  vercel.json
Labels: gssoc, level3

#105 fixed same background color for both modes in Signup page #100
  src/index.css
Labels: gssoc, level1

#108 Fix 🐞: Persist Theme Preference Across Page Reloads
  src/main.jsx
Labels: gssoc, level2

#112 Fix/issue #94 About and Career section made responsive
  src/Pages/AboutPage.jsx
  src/Pages/CareersPage.jsx
  src/components/Footer/Footer.jsx
Labels: gssoc, level2

#122 fixed issue #117 Updated the UI of the navbar -breaking at 768px of screen size- resolved
  src/components/Header/Header.jsx
  src/index.css
Labels: gssoc, level2

#72 Added Installation and Contribution steps in README.md
  README.md
Labels: gssoc, level1

#126 header-sticky-fixed
  src/index.css
Labels: gssoc, level1

#128 fix: added Lenis for smooth scroll
  package.json
  src/main.jsx
Labels: gssoc, level2

#141 Fix/issue #120 Image at landing page made responsive
  src/Pages/LandingPage.jsx
Labels: gssoc, level1

#149 added workflow as per issue #139
  .github/workflows/autocomment-iss-close.yml
Labels: gssoc, level1

#150 Relocated the theme button in menu on mobile
  src/components/Header/Header.jsx
  src/components/Header/MenuOverlay.jsx
Labels: gssoc, level2

#113 Added AI Chatbot
  package.json
  src/components/Layout.jsx
Labels: gssoc, level3

#157 Fixed 'Learn More' Scroll Issue Using react-scroll Components
  package.json
  src/Pages/LandingPage.jsx
Labels: gssoc, level2

#165 Redesigned the blog page.
  src/Pages/Blogs.jsx
Labels: gssoc, level2

#161 fix: greeting CI Activity
  .github/workflows/greetings.yml
Labels: gssoc, level1

#166 Added icons on the navbar
  index.html
  src/components/Header/Header.jsx
Labels: gssoc, level2

#172 Added FAQ page
  src/Pages/Faq.jsx
  src/Pages/Faqpage.jsx
  src/components/FAQ/Faqdata.js
  src/components/Footer/Footer.jsx
  src/main.jsx
  src/styles/Faq.css
Labels: gssoc, level2

#124 Patient Routes
  backend/routes/auth_routes.py
  backend/routes/patient_routes.py
Labels: gssoc, level3
