Repository Nactore-Org/Nacto-Care, pull requests merged in 2024-06, with the labels that each got.

#199 'Find your Home Care Taker' form fixed in dark theme
  src/components/Form/Form.jsx
Labels: gssoc, level2

#216 Redirecting social media links to a new tab
  src/components/Footer/Footer.jsx
Labels: gssoc, level1

#222 resized the hamburger menu button, form, and logo
  src/Pages/LandingPage.jsx
  src/components/Header/Header.jsx
Labels: gssoc, level2

#224 Adding social media icons to the footer
  package.json
  src/components/Footer/Footer.jsx
Labels: gssoc, level3

#227 added tabs in blogs section
  src/Pages/BlogPage.jsx
  src/Pages/Blogs.jsx
  src/components/SingleBlog.jsx
Labels: gssoc, level2

#237 Optimised the FAQ page for dark theme
  src/styles/Faq.css
Labels: level1

#234 Added blogs in blogs section
  src/Pages/BlogPage.jsx
  src/index.css
  src/styles/BrandCenter.css
Labels: gssoc, level2

#241 404 not found page added
  public/assets/404.webp
  src/Pages/NotFound.jsx
  src/main.jsx
Labels: gssoc, level2

#249 Re-designed Scroll-to-Top button
  src/ScrollToTopButton.jsx
Labels: gssoc, level2

#250 added validation for date and time fields for medical need form
  src/components/Form/Form.jsx
Labels: gssoc, level2

#258 Added User Testimonials Section
  src/components/Layout.jsx
  src/components/Testimonials/Testimonials.jsx
  src/components/Testimonials/testimonials.js
Labels: gssoc, level2
